
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.Notebook tabView;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label label3;
	private global::Gtk.FileChooserButton fileChooserButton;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button startStopButton;
	private global::Gtk.Button abortButton;
	private global::Gtk.Label GCodeStreamingTab;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Entry GCodeCommandEntry;
	private global::Gtk.Button sendButton;
	private global::Gtk.HBox hbox4;
	private global::Gtk.CheckButton prependG01Checkbutton;
	private global::Gtk.Label MillCommandLineFrame;
	private global::Gtk.HBox hbox7;
	private global::Gtk.VBox vbox6;
	private global::Gtk.Button motorOnButton;
	private global::Gtk.Button motorOffButton;
	private global::Gtk.Button panicButton;
	private global::Gtk.Frame frame2;
	private global::Gtk.VBox vbox5;
	private global::Gtk.Button xplusButton;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Button yplusButton;
	private global::Gtk.Button zminusButton;
	private global::Gtk.Button zplusButton;
	private global::Gtk.Button yminusButton;
	private global::Gtk.Button xminButton;
	private global::Gtk.HBox hbox6;
	private global::Gtk.ComboBoxEntry directControlMillimetersComboBoxEntry;
	private global::Gtk.Label directControlMillimetersComboBoxEntryLabel;
	private global::Gtk.Label DirectControlFrame;
	private global::Gtk.Label manualControlTab;
	private global::Gtk.ScrolledWindow terminalViewScrolledWindow;
	private global::Gtk.TextView terminalView;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.tabView = new global::Gtk.Notebook ();
		this.tabView.CanFocus = true;
		this.tabView.Name = "tabView";
		this.tabView.CurrentPage = 0;
		// Container child tabView.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.HeightRequest = 123;
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Select G-code file to be streamed below:");
		this.vbox3.Add (this.label3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fileChooserButton = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a File"), ((global::Gtk.FileChooserAction)(0)));
		this.fileChooserButton.Name = "fileChooserButton";
		this.vbox3.Add (this.fileChooserButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fileChooserButton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.startStopButton = new global::Gtk.Button ();
		this.startStopButton.Sensitive = false;
		this.startStopButton.CanFocus = true;
		this.startStopButton.Name = "startStopButton";
		this.startStopButton.UseUnderline = true;
		this.startStopButton.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox2.Add (this.startStopButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.startStopButton]));
		w3.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.abortButton = new global::Gtk.Button ();
		this.abortButton.Sensitive = false;
		this.abortButton.CanFocus = true;
		this.abortButton.Name = "abortButton";
		this.abortButton.UseUnderline = true;
		this.abortButton.Label = global::Mono.Unix.Catalog.GetString ("Abort");
		this.hbox2.Add (this.abortButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.abortButton]));
		w4.Position = 1;
		this.vbox3.Add (this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
		w5.Position = 2;
		w5.Expand = false;
		w5.Fill = false;
		this.tabView.Add (this.vbox3);
		global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.tabView [this.vbox3]));
		w6.TabFill = false;
		// Notebook tab
		this.GCodeStreamingTab = new global::Gtk.Label ();
		this.GCodeStreamingTab.Name = "GCodeStreamingTab";
		this.GCodeStreamingTab.LabelProp = global::Mono.Unix.Catalog.GetString ("G-code streaming");
		this.tabView.SetTabLabel (this.vbox3, this.GCodeStreamingTab);
		this.GCodeStreamingTab.ShowAll ();
		// Container child tabView.Gtk.Notebook+NotebookChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame1.BorderWidth = ((uint)(2));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GCodeCommandEntry = new global::Gtk.Entry ();
		this.GCodeCommandEntry.CanFocus = true;
		this.GCodeCommandEntry.Name = "GCodeCommandEntry";
		this.GCodeCommandEntry.IsEditable = true;
		this.GCodeCommandEntry.InvisibleChar = '•';
		this.hbox3.Add (this.GCodeCommandEntry);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GCodeCommandEntry]));
		w7.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.sendButton = new global::Gtk.Button ();
		this.sendButton.CanFocus = true;
		this.sendButton.Name = "sendButton";
		this.sendButton.UseUnderline = true;
		this.sendButton.Label = global::Mono.Unix.Catalog.GetString ("Send!");
		this.hbox3.Add (this.sendButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.sendButton]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox4.Add (this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
		w9.Position = 0;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.prependG01Checkbutton = new global::Gtk.CheckButton ();
		this.prependG01Checkbutton.CanFocus = true;
		this.prependG01Checkbutton.Name = "prependG01Checkbutton";
		this.prependG01Checkbutton.Label = global::Mono.Unix.Catalog.GetString ("Prepend G01");
		this.prependG01Checkbutton.DrawIndicator = true;
		this.prependG01Checkbutton.UseUnderline = true;
		this.hbox4.Add (this.prependG01Checkbutton);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.prependG01Checkbutton]));
		w10.Position = 0;
		this.vbox4.Add (this.hbox4);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		this.GtkAlignment.Add (this.vbox4);
		this.frame1.Add (this.GtkAlignment);
		this.MillCommandLineFrame = new global::Gtk.Label ();
		this.MillCommandLineFrame.Name = "MillCommandLineFrame";
		this.MillCommandLineFrame.LabelProp = global::Mono.Unix.Catalog.GetString ("Mill command line");
		this.MillCommandLineFrame.UseMarkup = true;
		this.frame1.LabelWidget = this.MillCommandLineFrame;
		this.vbox2.Add (this.frame1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame1]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.motorOnButton = new global::Gtk.Button ();
		this.motorOnButton.CanFocus = true;
		this.motorOnButton.Name = "motorOnButton";
		this.motorOnButton.UseUnderline = true;
		this.motorOnButton.Label = global::Mono.Unix.Catalog.GetString ("Turn motor ON");
		this.vbox6.Add (this.motorOnButton);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.motorOnButton]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.motorOffButton = new global::Gtk.Button ();
		this.motorOffButton.Sensitive = false;
		this.motorOffButton.CanFocus = true;
		this.motorOffButton.Name = "motorOffButton";
		this.motorOffButton.UseUnderline = true;
		this.motorOffButton.Label = global::Mono.Unix.Catalog.GetString ("Turn motor OFF");
		this.vbox6.Add (this.motorOffButton);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.motorOffButton]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.hbox7.Add (this.vbox6);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox6]));
		w17.Position = 0;
		w17.Expand = false;
		w17.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.panicButton = new global::Gtk.Button ();
		this.panicButton.CanFocus = true;
		this.panicButton.Name = "panicButton";
		this.panicButton.UseUnderline = true;
		// Container child panicButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w18 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w19 = new global::Gtk.HBox ();
		w19.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w20 = new global::Gtk.Image ();
		w20.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Menu);
		w19.Add (w20);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w22 = new global::Gtk.Label ();
		w22.LabelProp = global::Mono.Unix.Catalog.GetString ("Emergency stop");
		w22.UseUnderline = true;
		w19.Add (w22);
		w18.Add (w19);
		this.panicButton.Add (w18);
		this.hbox7.Add (this.panicButton);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.panicButton]));
		w26.Position = 1;
		this.vbox2.Add (this.hbox7);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
		w27.Position = 1;
		w27.Expand = false;
		w27.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w28.Position = 0;
		w28.Expand = false;
		w28.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(1));
		this.frame2.BorderWidth = ((uint)(2));
		// Container child frame2.Gtk.Container+ContainerChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.xplusButton = new global::Gtk.Button ();
		this.xplusButton.CanFocus = true;
		this.xplusButton.Name = "xplusButton";
		this.xplusButton.UseUnderline = true;
		// Container child xplusButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w30 = new global::Gtk.HBox ();
		w30.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w31 = new global::Gtk.Image ();
		w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
		w30.Add (w31);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w33 = new global::Gtk.Label ();
		w30.Add (w33);
		w29.Add (w30);
		this.xplusButton.Add (w29);
		this.vbox5.Add (this.xplusButton);
		global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.xplusButton]));
		w37.Position = 0;
		w37.Expand = false;
		w37.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.yplusButton = new global::Gtk.Button ();
		this.yplusButton.CanFocus = true;
		this.yplusButton.Name = "yplusButton";
		this.yplusButton.UseUnderline = true;
		// Container child yplusButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w39 = new global::Gtk.HBox ();
		w39.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w40 = new global::Gtk.Image ();
		w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
		w39.Add (w40);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w42 = new global::Gtk.Label ();
		w39.Add (w42);
		w38.Add (w39);
		this.yplusButton.Add (w38);
		this.hbox5.Add (this.yplusButton);
		global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.yplusButton]));
		w46.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.zminusButton = new global::Gtk.Button ();
		this.zminusButton.CanFocus = true;
		this.zminusButton.Name = "zminusButton";
		this.zminusButton.UseUnderline = true;
		this.zminusButton.Label = global::Mono.Unix.Catalog.GetString ("Down");
		this.hbox5.Add (this.zminusButton);
		global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.zminusButton]));
		w47.Position = 1;
		w47.Expand = false;
		w47.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.zplusButton = new global::Gtk.Button ();
		this.zplusButton.CanFocus = true;
		this.zplusButton.Name = "zplusButton";
		this.zplusButton.UseUnderline = true;
		this.zplusButton.Label = global::Mono.Unix.Catalog.GetString ("Up");
		this.hbox5.Add (this.zplusButton);
		global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.zplusButton]));
		w48.Position = 2;
		w48.Expand = false;
		w48.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.yminusButton = new global::Gtk.Button ();
		this.yminusButton.CanFocus = true;
		this.yminusButton.Name = "yminusButton";
		this.yminusButton.UseUnderline = true;
		// Container child yminusButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w49 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w50 = new global::Gtk.HBox ();
		w50.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w51 = new global::Gtk.Image ();
		w51.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
		w50.Add (w51);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w53 = new global::Gtk.Label ();
		w50.Add (w53);
		w49.Add (w50);
		this.yminusButton.Add (w49);
		this.hbox5.Add (this.yminusButton);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.yminusButton]));
		w57.Position = 3;
		this.vbox5.Add (this.hbox5);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox5]));
		w58.Position = 1;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.xminButton = new global::Gtk.Button ();
		this.xminButton.CanFocus = true;
		this.xminButton.Name = "xminButton";
		this.xminButton.UseUnderline = true;
		// Container child xminButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w59 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w60 = new global::Gtk.HBox ();
		w60.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w61 = new global::Gtk.Image ();
		w61.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
		w60.Add (w61);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w63 = new global::Gtk.Label ();
		w60.Add (w63);
		w59.Add (w60);
		this.xminButton.Add (w59);
		this.vbox5.Add (this.xminButton);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.xminButton]));
		w67.Position = 2;
		w67.Expand = false;
		w67.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.directControlMillimetersComboBoxEntry = global::Gtk.ComboBoxEntry.NewText ();
		this.directControlMillimetersComboBoxEntry.AppendText (global::Mono.Unix.Catalog.GetString ("0.1"));
		this.directControlMillimetersComboBoxEntry.AppendText (global::Mono.Unix.Catalog.GetString ("0.25"));
		this.directControlMillimetersComboBoxEntry.AppendText (global::Mono.Unix.Catalog.GetString ("0.5"));
		this.directControlMillimetersComboBoxEntry.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
		this.directControlMillimetersComboBoxEntry.AppendText (global::Mono.Unix.Catalog.GetString ("2.5"));
		this.directControlMillimetersComboBoxEntry.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
		this.directControlMillimetersComboBoxEntry.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
		this.directControlMillimetersComboBoxEntry.WidthRequest = 66;
		this.directControlMillimetersComboBoxEntry.Name = "directControlMillimetersComboBoxEntry";
		this.directControlMillimetersComboBoxEntry.Active = 1;
		this.hbox6.Add (this.directControlMillimetersComboBoxEntry);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.directControlMillimetersComboBoxEntry]));
		w68.Position = 0;
		w68.Expand = false;
		w68.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.directControlMillimetersComboBoxEntryLabel = new global::Gtk.Label ();
		this.directControlMillimetersComboBoxEntryLabel.Name = "directControlMillimetersComboBoxEntryLabel";
		this.directControlMillimetersComboBoxEntryLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Millimeters per shift ");
		this.hbox6.Add (this.directControlMillimetersComboBoxEntryLabel);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.directControlMillimetersComboBoxEntryLabel]));
		w69.Position = 1;
		w69.Expand = false;
		w69.Fill = false;
		this.vbox5.Add (this.hbox6);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox6]));
		w70.Position = 3;
		w70.Expand = false;
		w70.Fill = false;
		this.frame2.Add (this.vbox5);
		this.DirectControlFrame = new global::Gtk.Label ();
		this.DirectControlFrame.Name = "DirectControlFrame";
		this.DirectControlFrame.LabelProp = global::Mono.Unix.Catalog.GetString ("Direct mill control");
		this.DirectControlFrame.UseMarkup = true;
		this.frame2.LabelWidget = this.DirectControlFrame;
		this.hbox1.Add (this.frame2);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame2]));
		w72.Position = 1;
		w72.Expand = false;
		w72.Fill = false;
		this.tabView.Add (this.hbox1);
		global::Gtk.Notebook.NotebookChild w73 = ((global::Gtk.Notebook.NotebookChild)(this.tabView [this.hbox1]));
		w73.Position = 1;
		// Notebook tab
		this.manualControlTab = new global::Gtk.Label ();
		this.manualControlTab.Name = "manualControlTab";
		this.manualControlTab.LabelProp = global::Mono.Unix.Catalog.GetString ("manual control");
		this.tabView.SetTabLabel (this.hbox1, this.manualControlTab);
		this.manualControlTab.ShowAll ();
		this.vbox1.Add (this.tabView);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.tabView]));
		w74.Position = 0;
		w74.Expand = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.terminalViewScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.terminalViewScrolledWindow.CanFocus = true;
		this.terminalViewScrolledWindow.Name = "terminalViewScrolledWindow";
		this.terminalViewScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.terminalViewScrolledWindow.WindowPlacement = ((global::Gtk.CornerType)(3));
		// Container child terminalViewScrolledWindow.Gtk.Container+ContainerChild
		this.terminalView = new global::Gtk.TextView ();
		this.terminalView.CanFocus = true;
		this.terminalView.Name = "terminalView";
		this.terminalView.Editable = false;
		this.terminalViewScrolledWindow.Add (this.terminalView);
		this.vbox1.Add (this.terminalViewScrolledWindow);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.terminalViewScrolledWindow]));
		w76.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 493;
		this.DefaultHeight = 412;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.tabView.SwitchPage += new global::Gtk.SwitchPageHandler (this.onPageSwitch);
		this.fileChooserButton.SelectionChanged += new global::System.EventHandler (this.onFileActivated);
		this.startStopButton.Clicked += new global::System.EventHandler (this.onStartStopClicked);
		this.GCodeCommandEntry.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.GCodeCommandEntrykeyPressed);
		this.sendButton.Clicked += new global::System.EventHandler (this.sendButtonClicked);
		this.motorOnButton.Clicked += new global::System.EventHandler (this.turnMotorOnButtonWasClicked);
		this.motorOffButton.Clicked += new global::System.EventHandler (this.turnMotorOffButtonWasClicked);
		this.xplusButton.Clicked += new global::System.EventHandler (this.xplusButtonClicked);
		this.yplusButton.Clicked += new global::System.EventHandler (this.yplusButtonClicked);
		this.zminusButton.Clicked += new global::System.EventHandler (this.zminusButtonClicked);
		this.zplusButton.Clicked += new global::System.EventHandler (this.zplusButtonClicked);
		this.yminusButton.Clicked += new global::System.EventHandler (this.yminusButtonClicked);
		this.xminButton.Clicked += new global::System.EventHandler (this.xminusButtonClicked);
	}
}
